version: '3'
services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  back:
    build:
      context: ./back
    command: bash -c "tail -f log/development.log"
    volumes:
      - ./back:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
  front:
    build:
      dockerfile: ./front/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./front:/app
    ports:
      - '8000:3000'
volumes:
  mysql_data:
